### ISSUE TITLE
some discussions on new ops

### ISSUE THREAD

**Issue by njzjz** [wanghan-iapcm/dpgen2#1]
1. Deprecate old DeePMD-kit version: maybe we can deprecate DeePMD-kit 1.x here?
2. Use HDF5: see https://github.com/deepmodeling/dpgen/issues/617
3. Generate a single MD trajectory file instead multiple files: this is also better for supercomputer file system

**Comment by wanghan-iapcm** [comment]
1 and 3 support.
2 Please see my comment in the original discussion.
